version: '2'

services:
    mysql:
        image: mysql
        restart: always
        env_file:
           - variables.env
        # volumes:
        #     - ./data/mysql:/docker-entrypoint-initdb.d
    nginx:
        depends_on:
            - phpfpm
        image: nginx
        ports:
            - "80:80"
        restart: always
        working_dir: /var/www
        volumes:
            - ./magento2:/var/www/
            - ./conf/nginx/magento.conf:/etc/nginx/conf.d/default.conf
        
    phpfpm:
        image: phalconphp/php-apache:ubuntu-16.04
        restart: always
        working_dir: /var/www
        ports:
            - "8080:80"
        volumes:
            - ./magento2:/var/www
            - ./conf/php/fpm.ini://etc/php/7.0/fpm/php.ini
        depends_on:
            - mysql