version: '2'

services:

  mysql:
    image: mysql:5.7
    restart: always
    env_file:
      - variables.env
    volumes:
      - ./mysql/data:/var/lib/mysql
  nginx:
    depends_on:
      - phpfpm
    image: nginx
    ports:
      - "80:80"
    restart: always
    working_dir: /var/www
    volumes:
      - ./web/wordpress:/var/www
      - ./conf/nginx/wordpress.conf:/etc/nginx/conf.d/default.conf
  phpfpm:
    image: phalconphp/php-apache:ubuntu-16.04
    restart: always
    working_dir: /var/www
    ports:
      - "8080:80"
    volumes:
      - ./web/wordpress:/var/www
    depends_on:
      - mysql

   

